version: '3.7'
services:

  postgresSql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app


  mysqldb:
    image: mysql:latest
      ports:
        - '3306:3306'
          volumes:
            - ./msdata:/var/lib/mysql
          environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=pass

 node-app:
      build: .
      image: node-app:1.0
      ports:
        - '9999:9999'